---
- hosts: all
  tasks:
    - name: get disk usage
      command: df -h
      register: disk_usage

    - name: Check disk space
      shell: df -h / | awk 'NR==2 {print $5}'
      register: disk_usage
    - name: Display the outcome
      debug:
        msg: '{{ disk_usage }}'
