---
- name: Test SURVEY
  hosts: all
#  gather_facts: yes
  become: yes
#  become_user: root
#  become: true
#  become_method: enable
  tasks:

  - name: Repo Update
    apt:
      update_cache: yes

  - name: Upgrade all packages to the last version
    apt:
      name: "*"
      state: latest
