---
- name: windows rolling update
  hosts: all
  ansible_port: 5985
  ansible_connection: winrm
  ansible_winrm_server_cert_validation: ignore
  
  tasks:
    - name: Install all critical and security updates
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
        state: installed
        reboot: true
        log_path: C:\ansible.txt
